server:
  port: 7401

spring:
  application:
    name: gateway

#zuul:
 # routes:
 #   api-aaa:
  #    path: /user/**
   #   url: https://baidu.com/
    #   url: https://baidu.com/
  url: https://baidu.com/

zuul:
  routes:
    api-abc:
      path: /cons/**
      serviceId: eureka-consumer




eureka:
  client:
  # 注册中心地址
    serviceUrl:
      defaultZone: http://peer1:7101/eureka/,http://peer2:7102/eureka/
